services:
    autoBackup:
        container_name: auto_backup
        volumes:
            - ./logs/:/app/logs
        env_file:
            - ./.env
        restart: unless-stopped
        image: reg.reaweb.uk/auto_backup
        build:
            context: .
            dockerfile: Dockerfile
