version: "3"

services:
    autoReplicate:
        container_name: auto_replicate
        volumes:
            - ./logs/:/app/logs
        env_file:
            - ./.env
        restart: unless-stopped
        image: reg.reaweb.uk/auto_replicate
        build:
            context: .
            dockerfile: Dockerfile
